# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa5b0c162cb44c39d32059dd4f200d27859be56212237cf5489c574fbe7c5d57e644b2b76616e341fdcb991c6aa88d95944205915bf2f441393fc477b89e1ba

test:
  secret_key_base: 813f17b8221e6d8d0786fa22779c7b8823444aca1acfcef61174d098b595f6d5a7f4f0e30216dbf2cd0123da1daa0e0de8d20f3958bb3b776c72efe14cf4048a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
